/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

// For assistance: 
// Check the "Project Resources" section of the project instructions
// Reach out in your Slack community - https://treehouse-fsjs-102.slack.com/app_redirect?channel=chit-chat

/*** 
 * `quotes` array 
 * Array of quotes with properities such as source, year, citation and attempted to create tags
 ***/
const quotes = [
	{
		quote: 'You miss 100% of the shots you don\'t take.'
		, source: 'Wayne Gretzky'
  }
	, {
		quote: 'Whether you think you can or you think you can\'t, you\'re right.'
		, source: 'Henry Ford'
  }
	, {
		quote: 'I have learned over the years that when one\'s mind is made up, this diminishes fear.'
		, source: 'Rosa Parks'
  }
	, {
		quote: 'I alone cannot change the world, but I can cast a stone across the water to create many ripples.'
		, source: 'Mother Teresa'
  }
	, {
		quote: 'Your time is limited, so don\'t waste it living someone else\'s life. Don\'t be trapped by dogma – which is living with the results of other people\'s thinking.'
		, source: 'Steve Jobs'
  }
	, {
		quote: 'If life were predictable it would cease to be life, and be without flavor.'
		, source: 'Eleanor Roosevelt'
  }
	, {
		quote: 'If you look at what you have in life, you\'ll always have more. If you look at what you don\'t have in life, you\'ll never have enough.'
		, source: 'Oprah Winfrey'
  }
	, {
		quote: 'Mama, mama, mama, mama'
		, source: 'Javi Lopez'
		, year: '2021'
    	, tags: 'humor'
  }
	, {
		quote: 'It\'s the climb'
		, source: 'Miley Cyrus'
		, citation: 'Hannah Montana: The Movie'
		, year: '2005'
  }
]

const backgroundColors = [ "#D94D30", "#F5E973", "#B0DF29", "#1FC8B3", "#10AFE2", "#4B84F5", "#59338B", "#8619AF", "#BD1274" ];

/***
 * `getRandomQuote` function generates random quotes from the quotes array
 * param: takes in an array of quotes 
 * return: returns a random quote from the index generated by a random number
 ***/
const getRandomQuote = ( arr ) => {
  let randomIndex = Math.floor( Math.random() * arr.length );
	return arr[ randomIndex ];
}

/***
 * ORIGINAL PRINT QUOTE FUNCTION
 * `printQuote` function prints the random quote 
 * param: none
 * returns: a newly generated HTML text that plugs in whatever properties the object has 
 ***/
// function printQuote() {
// 	let randomQuote = getRandomQuote( quotes );

//   //source html phrase 
// 	let quoteView = `<p class=\"quote\"> ${ randomQuote["quote"] } </p> \n<p class=\"source\"> ${ randomQuote["source"] } `;

//   //conditional statement that plugs in HTML from properties of the object (randomQuote) randomly generated 
//   if ( randomQuote.hasOwnProperty( 'citation' ) === true && randomQuote.hasOwnProperty( 'year' ) === true && randomQuote.hasOwnProperty( 'tags' ) === true ) {
//     quoteView += `\n\t<span class=\"citation\"> ${ randomQuote["citation"] } </span>\n\t<span class=\"year\"> ${ randomQuote["year"] } </span>\n\t<span class=\"tags\"> ${ randomQuote["tags"] } </span>\n</p>`;
//   } else if ( randomQuote.hasOwnProperty( 'citation' ) === true && randomQuote.hasOwnProperty( 'year' ) === true ) {
// 		quoteView += `\n\t<span class=\"citation\"> ${ randomQuote["citation"] } </span>\n\t<span class=\"year\"> ${ randomQuote["year"] } </span>\n</p>`;
// 	} else if ( randomQuote.hasOwnProperty( 'citation' ) ) {
// 		quoteView += `\n\t<span class=\"citation\"> ${ randomQuote["citation"] } </span>\n</p>`;
// 	} else if ( randomQuote.hasOwnProperty( 'year' ) ) {
// 		quoteView += `\n\t<span class=\"year\"> ${ randomQuote["year"] } </span>\n</p>`;
// 	} else {
// 		quoteView += `</p>`
// 	}

// 	return document.getElementById( 'quote-box' ).innerHTML = quoteView;
// }

/***
 * CLEANER VERSION OF printQuote FUNCTION
 * `printQuote` function prints the random quote 
 * param: none
 * returns: a newly generated HTML text that plugs in whatever properties the object has 
 ***/
function printQuote() {
	let randomQuote = getRandomQuote( quotes );
	const hasCitation = randomQuote.hasOwnProperty( 'citation' ); 
	const hasYear = randomQuote.hasOwnProperty( 'year' );
	const hasTags = randomQuote.hasOwnProperty( 'tags' );

	console.log( randomQuote ); //for debugging
	
  	//source html phrase 
	let quoteView = `<p class=\"quote\"> ${ randomQuote["quote"] } </p> \n<p class=\"source\"> ${ randomQuote["source"] } `;

	if ( hasCitation ) {
		quoteView += `\n\t<span class=\"citation\"> ${ randomQuote["citation"] } </span>`;
	}

	if ( hasYear ) {
		quoteView += `\n\t<span class=\"year\"> ${ randomQuote["year"] } </span>`;
	}
	
	if ( hasTags ) {
		quoteView += `\n\t<span class=\"tags\"> ${ randomQuote["tags"] } </span>`;
	}

	quoteView += "\n</p>";

	console.log( quoteView ); //for debugging
	return document.getElementById( 'quote-box' ).innerHTML = quoteView;
}

/***
 * `changeBackgroundColor` function generates a random color and changes the background color from an array
 * param: array of colors
 * return: a randomly generated color from the array
 */
const changeBackgroundColor = ( arr ) => {
  let randomIndex = Math.floor(Math.random() * arr.length);
  return document.body.style.backgroundColor = arr[randomIndex];
}

/***
 * click event listener for the print quote button
 * DO NOT CHANGE THE CODE BELOW!!
 ***/
// document.getElementById( 'load-quote' ).addEventListener( "click", () => {
//   changeBackgroundColor( backgroundColors );
//   printQuote();
// }, false );

/***
 * prints out quotes every 3000 seconds
 ***/
setInterval( () => {
	changeBackgroundColor( backgroundColors );
	printQuote();
}, 3000);

